### ISSUE TITLE
w5500 lib for Arduino ESP core

### ISSUE THREAD

**Issue by mkeyno** [Serasidis/Ethernet_STM#1]
hi, do you have any interested to modified Ethernet (w5500) library to run on the ESP8266

esp8266/Arduino@2a01c2a

**Comment by Serasidis** [comment]
That would be good idea. I wish I had more free time ...

**Comment by mkeyno** [comment]
I hope so , but I'm sure you well aware about esp8266/Arduino library , most guys immigrate from old Arduino to it , I've tried to make adapter to convert Ethernet to ESP wifi node so I could sort it out all my wire devices , please let me know if you have any update on this lib,
