### ISSUE TITLE
Duplicate pinMode in w5100.begin

### ISSUE THREAD

**Issue by stevstrong** [Serasidis/Ethernet_STM#2]
https://github.com/Serasidis/Ethernet_STM/blob/master/src/utility/w5100.cpp#L39
and
https://github.com/Serasidis/Ethernet_STM/blob/master/src/utility/w5100.cpp#L44
I think one of them is superfluous.

**Comment by Serasidis** [comment]
Fixed. Thanks Steve !

**Comment by stevstrong** [comment]
I add the link to the fix, just for info.
https://github.com/Serasidis/Ethernet_STM/commit/d2edc84b3a1b35c488a12c611ea08972a3958f4e
