### ISSUE TITLE
Response buffer data problem

### ISSUE THREAD

**Issue by furkan-34** [Serasidis/Ethernet_STM#5]
Hello,
I have STM32F103C and working with your librariy (thanks for that). I try to get my string data from local php page with web client example. Php page only print 12345678- a couple times, but I can not see whole data. I see data length but not full data. How can I see all response string data ?

Results:
`<<< REQ >>>
HTTP/1.1 200 OK
Date: Tue, 11 Feb 2020 11:13:36 GMT
Server: Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.3.11
X-Powered-By: PHP/7.3.11
Content-Length: 81
Connection: close
Content-Type: text/html; charset=UTF-8

12345678-12345678-12345678-12345678-12345678-12345678-12345678-12345678-12345678-...
`

**Comment by Serasidis** [comment]
Are you referring to Ethercard or Ethernet_STM32 library ?

**Comment by furkan-34** [comment]
Ethernet_STM32 library. I found the solution:
I set

```
bool EtherCard::persist_tcp_connection = true; at EtherCard.cpp
Ethernet::buffer[off+len] = 0;
and byte Ethernet::buffer[9000]
```
and it worked very well.

Thank you for made this library.
